version: '3.7'

services:
  meilisearch:
    image: getmeili/meilisearch:v1.11
    container_name: meilisearch
    restart: unless-stopped
    networks:
      - meilisearch-net
    ports:
      - "7700:7700"
    environment:
      MEILI_ENV: "development"
      MEILI_MASTER_KEY: "your-key-is-here"
    volumes:
      - ./meili_data:/meili_data

  meilisearch-ui:
    image: riccoxie/meilisearch-ui:latest
    container_name: meilisearch-ui
    restart: always
    networks:
      - meilisearch-net
    ports:
      - "8080:24900"
    environment:
      MEILISEARCH_URL: "http://meilisearch:7700"

networks:
  meilisearch-net:

