services:
  meilisearch:
        container_name: meilisearch
        image: 'getmeili/meilisearch:v1.12.8'
        # deploy:
        #     resources:
        #         limits:
        #             cpus: "1"
        #             memory: 2048M
        restart: unless-stopped
        ports:
            - '7700:7700'
        environment:
            MEILI_NO_ANALYTICS: 'false'
        volumes:
            - 'meilisearch_data:/meili_data'
        networks:
          - microservices-network
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://127.0.0.1:7700/health'
            retries: 3
            timeout: 5s

networks:
    microservices-network:
        external: true

volumes:
    meilisearch_data:
        driver: local
