services:
  meilisearch:
        container_name: meilisearch
        image: 'getmeili/meilisearch:v1.12'
        # deploy:
        #     resources:
        #         limits:
        #             cpus: "1"
        #             memory: 2048M
        restart: unless-stopped
        ports:
            - '7700:7700'
        environment:
          MEILI_NO_ANALYTICS: 'false'
          MEILI_ENV: 'development'
          MEILI_MASTER_KEY: 'masterKey'
        volumes:
            - 'meilisearch_data:/meili_data'
        networks:
          - microservices-network
          - meilisearch-net
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://127.0.0.1:7700/health'
            retries: 3
            timeout: 5s
  meilisearch-ui:
    image: riccoxie/meilisearch-ui:latest
    container_name: meilisearch-ui
    restart: always
    networks:
      - microservices-network
      - meilisearch-net
    ports:
      - "24900:24900"
    environment:
      MEILISEARCH_URL: "http://meilisearch:7700"

networks:
    microservices-network:
        external: true
    meilisearch-net:
        driver: bridge

volumes:
    meilisearch_data:
        driver: local
